export const SOCKET_ACTION = {
  ADD_NEW_USER: 'ADD_NEW_USER',
  RECEIVE_ONLINE_USERS: 'RECEIVE_ONLINE_USERS',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVE_MESSAGES: 'RECEIVE_MESSAGES',
};

export const CONNECT = 'connect';
export const DISCONNECT = 'disconnect';
