import {
  PictureOutlined,
  UserOutlined,
  BankOutlined,
  SolutionOutlined,
  ReadOutlined,
  BookOutlined,
  TeamOutlined,
  EditOutlined,
  FileTextOutlined,
  MedicineBoxOutlined,
  HeartOutlined,
  CopyOutlined,
  ExperimentOutlined,
  HistoryOutlined,
  GlobalOutlined,
  CoffeeOutlined,
} from '@ant-design/icons';
import { IBookTypes } from '../interfaces';
import { v4 } from 'uuid';

export const BOOK_TYPES: IBookTypes[] = [
  {
    id: v4(),
    label: 'Art & Photography',
    description: 'Books on art and photography.',
    link: '/art-photography',
    icon: <PictureOutlined />,
  },
  {
    id: v4(),
    label: 'Biographies & Memoirs',
    description: 'Books about lives of notable individuals.',
    link: '/biographies-memoirs',
    icon: <UserOutlined />,
  },
  {
    id: v4(),
    label: 'Business & Economics',
    description: 'Books on business and economics.',
    link: '/business-economics',
    icon: <BankOutlined />,
  },
  {
    id: v4(),
    label: 'How-to - Self Help',
    description: 'Self-help and how-to books.',
    link: '/how-to-self-help',
    icon: <SolutionOutlined />,
  },
  {
    id: v4(),
    label: "Children's Books",
    description: 'Books for children.',
    link: '/childrens-books',
    icon: <ReadOutlined />,
  },
  {
    id: v4(),
    label: 'Dictionary',
    description: 'Dictionaries and thesauruses.',
    link: '/dictionary',
    icon: <BookOutlined />,
  },
  {
    id: v4(),
    label: 'Education - Teaching',
    description: 'Books on education and teaching methods.',
    link: '/education-teaching',
    icon: <TeamOutlined />,
  },
  {
    id: v4(),
    label: 'Fiction - Literature',
    description: 'Fictional and literary works.',
    link: '/fiction-literature',
    icon: <EditOutlined />,
  },
  {
    id: v4(),
    label: 'Magazines',
    description: 'Various magazines.',
    link: '/magazines',
    icon: <FileTextOutlined />,
  },
  {
    id: v4(),
    label: 'Medical Books',
    description: 'Books on medical topics.',
    link: '/medical-books',
    icon: <MedicineBoxOutlined />,
  },
  {
    id: v4(),
    label: 'Parenting & Relationships',
    description: 'Books on parenting and relationships.',
    link: '/parenting-relationships',
    icon: <HeartOutlined />,
  },
  {
    id: v4(),
    label: 'Reference',
    description: 'Reference books and materials.',
    link: '/reference',
    icon: <CopyOutlined />,
  },
  {
    id: v4(),
    label: 'Science - Technology',
    description: 'Books on science and technology.',
    link: '/science-technology',
    icon: <ExperimentOutlined />,
  },
  {
    id: v4(),
    label: 'History, Politics & Social Sciences',
    description: 'Books on history, politics, and social sciences.',
    link: '/history-politics-social-sciences',
    icon: <HistoryOutlined />,
  },
  {
    id: v4(),
    label: 'Travel & Holiday',
    description: 'Travel guides and holiday books.',
    link: '/travel-holiday',
    icon: <GlobalOutlined />,
  },
  {
    id: v4(),
    label: 'Cookbooks, Food & Wine',
    description: 'Books on cooking, food, and wine.',
    link: '/cookbooks-food-wine',
    icon: <CoffeeOutlined />,
  },
];
