import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Wrapper from '@/components/app/Wrapper';
import 'antd/dist/reset.css';
import Container from './Container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <Container>{children}</Container>
        </Wrapper>
      </body>
    </html>
  );
}
